name:                haskell-download-manager
version:             0.1.0.0
github:              "githubuser/haskell-download-manager"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-download-manager#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- io-streams
- http-conduit
- conduit
- stm
- fast-logger
- transformers
- exceptions
- temporary
- utf8-string
- random
- either
- filepath
- directory
- global-lock
- clock
- brick
- vty
- vector
- microlens
- microlens-th

library:
  source-dirs: src

executables:
  haskell-download-manager-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - haskell-download-manager

tests:
  haskell-download-manager-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    dependencies:
    - haskell-download-manager
